language: python
python:
  - 2.7
  - 3.2

notifications:
  email: false

# Install stuff
virtualenv:
  system_site_packages: true
before_install:
  - travis/install_sge.sh
  - export GRID_MAP_REDIS_PORT=12345
  - sudo mkdir /scratch/
  - sudo chmod 777 /scratch/
install:
  - pip install -r requirements.txt --use-mirrors
  - pip install python-coveralls --use-mirrors
  - pip install nose-cov --use-mirrors
  - python setup.py install

# Run test
script:
  - nosetests -d -v --with-cov --cov gridmap --cov-config .coveragerc

# Calculate coverage
after_success:
  - coveralls --config_file .coveragerc

# Print out scratch job info if failed
after_failure:
  - tail -n 1000 /scratch/*

